name: Linting

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

#      - name: Python Linting
#        uses: WhyNotHugo/python-linting@v1.0.0

      - name: Lint with flake8
        run: |
          python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          python -m flake8 . --count --exclude=app/db/migrations/ --max-complexity=10 --max-line-length=127 --statistics
